name: spectra-viewer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - matplotlib
  - plotly
  - openpyxl
  - xlrd
  - pip
  - pip:
    - PyQt5
    - PyQtWebEngine
